name: "Release Notes to Project Action"
description: "Processes release notes to update GitHub Project items based on linked issues and pull requests"
branding:
  icon: "git-pull-request"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token with repository and project permissions"
    required: true
  project-number:
    description: "GitHub Project number"
    required: true
  organization:
    description: "GitHub organization name (if using organization project)"
    required: false
  status-field-name:
    description: "Name of the status field in the project"
    required: true
    default: "Status"
  target-status:
    description: "Status to set for the project items"
    required: true
    default: "Deployed to Production"
  release-url:
    description: "GitHub release URL (alternative to using release event)"
    required: false
  release-notes:
    description: "Release notes content (alternative to using release URL or release event)"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
